config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :subscriptions
  resources :comments
  devise_for :users

  root "events#index"

  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end
  resources :users, only: %i[show edit update]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one_attached :photo do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
  end

  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :user, presence: true

  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, except: %i[index new create]

  skip_before_action :verify_authenticity_token

  after_action :verify_authorized, only: %i[edit update destroy show]

  def index
    @events = Event.all
  end

  def show
    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    authorize @event

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])

  rescue Pundit::NotAuthorizedError
    flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
    render 'password_form'
  end

  def new
    @event = current_user.events.build
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: I18n.t('controllers.events.created') }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @event

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: I18n.t('controllers.events.updated') }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @event
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: I18n.t('controllers.events.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :address, :datetime, :description, :photo, :pincode)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4 col-lg-4">
  <div class="card card h-100 img-thumbnail bg-transparent">

    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>


    <div class="thumbnail-inner event-info-inner h-100">
      <div class="card-body">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3 class="fs-6"><%= l event.datetime, format: :short %></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "#{I18n.t('forms.buttons.save')}", class: 'btn btn-primary' %>
    <%= I18n.t('forms.text.or') %> <%= link_to "#{I18n.t('forms.links.back')}", :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= I18n.t('forms.headers.events.edit') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= I18n.t('forms.headers.events.index') %></h1>

<div class="buffer-both">
  <%= link_to "#{I18n.t('forms.buttons.create_event')}", new_event_path, class: 'btn btn-success' %>
</div>

<div class="row">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= I18n.t('forms.headers.events.new') %></h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1><%= t('forms.headers.events.pincode_access') %></h1>

<%= form_tag('', method: 'post', data: { turbo:false }) do |f| %>
  <div class="form-group">
    <%= label t('views.labels.pincode'), :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

<%= link_to t('forms.links.main'), events_path %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
                      style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3>
              <small><%= link_to @event.address,
                                 "https://yandex.ru/maps/?text=#{@event.address}" %></small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="container buffer-both">
              <div class="row">
                <div class="col-lg-3">
                  <%= link_to t('forms.buttons.edit'), edit_event_path(@event),
                          class: 'btn btn-primary btn-block mr-3' %>
                </div>

                <div class="col-lg-3">
                  <%= button_to t('forms.buttons.delete'), event_path(@event), method: :delete,
                          class: 'btn btn-danger btn-block',
                                form: { data: {turbo_confirm: t('events.event.destroy_confirm')} } %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="event-photo-form">
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>

        <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
      </div>

      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
                   locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment',
                     collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4><%= t('views.event.invites') %></h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h4><%= t('views.event.subscribers') %></h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>

      <% unless this_is_current_user?(@event) || @event.subscribers.include?(current_user) %>
        <div class="event-subscription-form">
          <h4><%= t('views.event.subscribe') %></h4>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>

      <% if @event.photo.attached? %>
        <%= image_tag @event.photo %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <h4><%= t('views.event.location') %></h4>

    <div id="map" class="map"
    data-address="<%= @event.address %>">
    </div>
  </div>
</div>